Repository cerberus-org/cerberus-app, pull requests merged in 2018-02, with the labels that each got.

#224 Replace require with ES6 import
  .travis.yml
  src/app/containers/check-in/check-in.component.ts
Labels: bug

#226 Codecov integration
  .travis.yml
  README.md
  karma.conf.js
  yarn.lock
Labels: tools

#228 Export visit history as csv
  src/app/actions/settings.actions.ts
  src/app/app.module.ts
  src/app/components/reports-form/reports-form.component.html
  src/app/components/reports-form/reports-form.component.spec.ts
  src/app/components/reports-form/reports-form.component.ts
  src/app/containers/settings-page/settings-page.component.html
  src/app/containers/settings-page/settings-page.component.spec.ts
  src/app/containers/settings-page/settings-page.component.ts
  src/app/effects/settings.effects.spec.ts
  src/app/effects/settings.effects.ts
  src/app/functions/transducer.spec.ts
  src/app/functions/transducer.ts
  src/app/models/report.ts
  src/app/reducers/settings.reducer.spec.ts
  src/app/reducers/settings.reducer.ts
  src/app/services/csv.service.spec.ts
  src/app/services/csv.service.ts
Labels: feature

#231 Style enhancements
  karma.conf.js
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.spec.ts
  src/app/components/about-us/about-us.component.html
  src/app/components/about-us/about-us.component.scss
  src/app/components/check-in-form/check-in-form.component.html
  src/app/components/check-in-form/check-in-form.component.scss
  src/app/components/header/header.component.html
  src/app/components/header/header.component.spec.ts
  src/app/components/header/header.component.ts
  src/app/components/new-volunteer-form/new-volunteer-form.component.html
  src/app/components/organization-form/organization-form.component.html
  src/app/components/organization-form/organization-form.component.scss
  src/app/components/reports-form/reports-form.component.html
  src/app/components/reports-form/reports-form.component.scss
  src/app/components/sidenav/sidenav.component.html
  src/app/components/sidenav/sidenav.component.ts
  src/app/components/user-form/user-form.component.html
  src/app/components/user-form/user-form.component.scss
  src/app/containers/check-in/check-in.component.html
  src/app/containers/check-in/check-in.component.scss
  src/app/containers/data-display/data-display.component.scss
  src/app/containers/getting-started/getting-started.component.html
  src/app/containers/getting-started/getting-started.component.scss
  src/app/containers/login/login.component.html
  src/app/containers/login/login.component.scss
  src/app/containers/organization-dashboard/organization-dashboard.component.scss
  src/app/containers/organization-dashboard/organization-dashboard.component.ts
  src/app/containers/settings-page/settings-page.component.html
  src/app/containers/settings-page/settings-page.component.scss
  src/app/containers/settings-page/settings-page.component.ts
  src/styles.scss
Labels: enhancement

#232 Model reducer
  src/app/actions/app.actions.ts
  src/app/actions/auth.actions.ts
  src/app/actions/check-in.actions.ts
  src/app/actions/data-display.actions.ts
  src/app/actions/login.actions.ts
  src/app/actions/model.actions.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/check-in-form/check-in-form.component.html
  src/app/containers/check-in/check-in.component.ts
  src/app/containers/data-display/data-display.component.ts
  src/app/containers/getting-started/getting-started.component.ts
  src/app/containers/login/login.component.html
  src/app/containers/login/login.component.ts
  src/app/containers/organization-dashboard/organization-dashboard.component.ts
  src/app/containers/settings-page/settings-page.component.html
  src/app/containers/settings-page/settings-page.component.ts
  src/app/containers/verification-dialog/verification-dialog.component.ts
  src/app/effects/auth.effects.spec.ts
  src/app/effects/auth.effects.ts
  src/app/effects/check-in.effects.spec.ts
  src/app/effects/check-in.effects.ts
  src/app/effects/data-display.effects.spec.ts
  src/app/effects/data-display.effects.ts
  src/app/effects/getting-started.effects.spec.ts
  src/app/effects/login.effects.spec.ts
  src/app/effects/mock-services.ts
  src/app/effects/model.effects.spec.ts
  src/app/effects/model.effects.ts
  src/app/effects/settings.effects.spec.ts
  src/app/effects/settings.effects.ts
  src/app/functions/helpers.ts
  src/app/models/user.ts
  src/app/reducers/app.reducer.spec.ts
  src/app/reducers/app.reducer.ts
  src/app/reducers/auth.reducer.spec.ts
  src/app/reducers/auth.reducer.ts
  src/app/reducers/check-in.reducer.spec.ts
  src/app/reducers/check-in.reducer.ts
  src/app/reducers/data-display.reducer.spec.ts
  src/app/reducers/data-display.reducer.ts
  src/app/reducers/index.ts
  src/app/reducers/model.reducer.spec.ts
  src/app/reducers/model.reducer.ts
  src/app/reducers/settings.reducer.spec.ts
  src/app/reducers/settings.reducer.ts
  src/app/services/auth.service.ts
  src/app/services/organization.service.ts
  src/app/services/site.service.ts
  src/app/services/user.service.ts
  src/app/services/visit.service.ts
  src/app/services/volunteer.service.ts
Labels: enhancement

#236 Roles and responsibilities
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/user-form/user-form.component.spec.ts
  src/app/components/user-form/user-form.component.ts
  src/app/containers/index.ts
  src/app/containers/join-page/join-page.component.html
  src/app/containers/join-page/join-page.component.scss
  src/app/containers/join-page/join-page.component.spec.ts
  src/app/containers/join-page/join-page.component.ts
  src/app/containers/login/login.component.html
  src/app/containers/login/login.component.ts
  src/app/effects/getting-started.effects.ts
  src/app/effects/login.effects.spec.ts
  src/app/effects/login.effects.ts
  src/app/models/user.ts
  src/app/services/auth.service.ts
  src/app/services/base.service.ts
  src/app/services/snack-bar.service.ts
Labels: feature
