Repository cerberus-org/cerberus-app, pull requests merged in 2018-04, with the labels that each got.

#256 Add tos to join org
  src/app/containers/join-page/join-page.component.html
  src/app/containers/join-page/join-page.component.spec.ts
  src/app/containers/join-page/join-page.component.ts
Labels: enhancement

#258 Fix Codecov - add code coverage flag to test:ci script
  package.json
Labels: bug

#259 Data display enhancements
  src/app/app.component.ts
  src/app/components/check-in-form/check-in-form.component.html
  src/app/components/daily-hours-chart/daily-hours-chart.component.html
  src/app/components/daily-hours-chart/daily-hours-chart.component.scss
  src/app/components/data-table/data-table.component.html
  src/app/components/data-table/data-table.component.ts
  src/app/components/header/header.component.html
  src/app/components/volunteer-menu/volunteer-menu.component.html
  src/app/containers/check-in/check-in.component.html
  src/app/containers/check-in/check-in.component.scss
  src/app/containers/check-in/check-in.component.ts
  src/app/containers/organization-dashboard/organization-dashboard.component.ts
Labels: bug, enhancement
