Repository cerberus-org/cerberus-app, pull requests merged in 2018-08, with the labels that each got.

#314 Edit site visits
  src/app/core/services/snack-bar.service.ts
  src/app/settings/actions/settings.actions.ts
  src/app/settings/components/site-dialog/site-dialog.component.html
  src/app/settings/components/visit-dialog/visit-dialog.component.html
  src/app/settings/components/visit-dialog/visit-dialog.component.scss
  src/app/settings/components/visit-dialog/visit-dialog.component.spec.ts
  src/app/settings/components/visit-dialog/visit-dialog.component.ts
  src/app/settings/containers/site-settings/site-settings.component.ts
  src/app/settings/containers/visits/visits.component.html
  src/app/settings/containers/visits/visits.component.spec.ts
  src/app/settings/containers/visits/visits.component.ts
  src/app/settings/effects/settings.effects.ts
  src/app/settings/selectors/visits.selectors.spec.ts
  src/app/settings/selectors/visits.selectors.ts
  src/app/settings/settings.module.ts
  src/app/shared/components/data-cell/data-cell.component.html
  src/app/shared/components/data-cell/data-cell.component.spec.ts
  src/app/shared/components/data-cell/data-cell.component.ts
  src/app/shared/components/data-table/data-table.component.html
  src/app/shared/components/data-table/data-table.component.scss
  src/app/shared/components/data-table/data-table.component.spec.ts
  src/app/shared/components/data-table/data-table.component.ts
  src/app/shared/models/visit-with-volunteer.ts
Labels: enhancement

#319 Handle undefined user info values in auth state
  src/app/auth/effects/auth.effects.ts
  src/app/auth/selectors/auth.selectors.ts
  src/app/core/selectors/members.selectors.ts
  src/app/settings/selectors/user-settings.selectors.ts
  src/app/teams/effects/teams-page.effects.ts
Labels: bug

#324 Add environment for develop production mode and update scripts
  .travis.yml
  angular.json
  package.json
  src/app/app.module.ts
  src/app/auth/effects/auth.effects.ts
  src/app/core/containers/header/header.component.ts
  src/app/core/containers/sidenav/sidenav.component.ts
  src/app/core/services/app-update.service.spec.ts
  src/app/core/services/app-update.service.ts
  src/app/settings/containers/edit-visit-dialog/edit-visit-dialog.component.ts
  src/app/teams/containers/teams-page/teams-page.component.ts
  src/app/teams/containers/view-selected-team/view-selected-team.component.ts
  src/environments/environment.develop.ts
  src/environments/environment.production.ts
  src/environments/environment.ts
Labels: tools

#323 Copy and paste from closed PR
  src/app/public/containers/home-page/home-page.component.scss
  src/app/public/containers/view-activity-page/view-activity-page.component.html
  src/app/public/containers/view-activity-page/view-activity-page.component.spec.ts
  src/app/public/containers/view-activity-page/view-activity-page.component.ts
  src/app/shared/components/daily-hours-chart/daily-hours-chart.component.spec.ts
  src/app/shared/components/daily-hours-chart/daily-hours-chart.component.ts
  src/app/shared/components/data-display/data-display.component.html
  src/app/shared/components/data-display/data-display.component.spec.ts
  src/app/shared/components/data-display/data-display.component.ts
  src/app/teams/containers/view-selected-team/view-selected-team.component.spec.ts
  src/app/teams/containers/view-selected-team/view-selected-team.component.ts
  src/app/volunteers/containers/team-dashboard-page/team-dashboard-page.component.spec.ts
  src/app/volunteers/containers/team-dashboard-page/team-dashboard-page.component.ts
Labels: feature

#326 Set single site
  src/app/core/actions/sites.actions.ts
  src/app/core/reducers/sites.reducer.ts
  src/app/core/selectors/sites.selectors.ts
  src/app/core/selectors/visits.selectors.ts
  src/app/volunteers/containers/check-in-page/check-in-page.component.ts
  src/app/volunteers/containers/team-dashboard-page/team-dashboard-page.component.ts
  src/app/volunteers/effects/check-in.effects.ts
Labels: enhancement

#328 Allow user to deselect site
  src/app/teams/components/selected-team-toolbar/selected-team-toolbar.component.ts
Labels: enhancement
