Repository cerberus-org/cerberus-app, pull requests merged in 2018-07, with the labels that each got.

#295 Check-in enhancements
  package.json
  src/app/functions/helpers.functions.spec.ts
  src/app/functions/helpers.functions.ts
  src/app/mock/objects/volunteer.mock.ts
  src/app/root/containers/header/header.component.html
  src/app/root/containers/header/header.component.scss
  src/app/root/containers/header/header.component.spec.ts
  src/app/root/containers/header/header.component.ts
  src/app/root/containers/root/root.component.html
  src/app/root/containers/root/root.component.spec.ts
  src/app/root/store/selectors/layout.selectors.ts
  src/app/sign-up/containers/getting-started/getting-started.component.ts
  src/app/volunteer-system/components/check-in-form/check-in-form.component.html
  src/app/volunteer-system/components/check-in-form/check-in-form.component.scss
  src/app/volunteer-system/components/check-in-form/check-in-form.component.spec.ts
  src/app/volunteer-system/components/check-in-form/check-in-form.component.ts
  src/app/volunteer-system/components/new-volunteer-form/new-volunteer-form.component.html
  src/app/volunteer-system/components/new-volunteer-form/new-volunteer-form.component.scss
  src/app/volunteer-system/components/signature-field/signature-field.component.html
  src/app/volunteer-system/components/signature-field/signature-field.component.scss
  src/app/volunteer-system/components/signature-field/signature-field.component.spec.ts
  src/app/volunteer-system/components/signature-field/signature-field.component.ts
  src/app/volunteer-system/containers/check-in/check-in.component.html
  src/app/volunteer-system/containers/check-in/check-in.component.scss
  src/styles.scss
Labels: enhancement

#296 Fix member data load
  src/app/auth/store/effects/session.effects.spec.ts
  src/app/auth/store/effects/session.effects.ts
  src/app/volunteer-system/containers/check-in/check-in.component.html
  src/app/volunteer-system/containers/check-in/check-in.component.scss
Labels: bug

#294 Vist table wrap up
  src/app/functions/date-format.functions.spec.ts
  src/app/functions/date-format.functions.ts
  src/app/functions/helpers.functions.spec.ts
  src/app/functions/helpers.functions.ts
  src/app/home/containers/home/home.component.html
  src/app/home/containers/home/home.component.spec.ts
  src/app/home/containers/home/home.component.ts
  src/app/models/column-options.ts
  src/app/models/visit-with-volunteer.ts
  src/app/settings/containers/roles/roles.component.html
  src/app/settings/containers/roles/roles.component.spec.ts
  src/app/settings/containers/visits/visits.component.html
  src/app/settings/containers/visits/visits.component.spec.ts
  src/app/settings/containers/visits/visits.component.ts
  src/app/settings/store/selectors/visits.selectors.spec.ts
  src/app/settings/store/selectors/visits.selectors.ts
  src/app/shared/components/data-cell/data-cell.component.html
  src/app/shared/components/data-cell/data-cell.component.spec.ts
  src/app/shared/components/data-cell/data-cell.component.ts
  src/app/shared/components/data-table/data-table.component.html
  src/app/shared/components/data-table/data-table.component.scss
  src/app/shared/components/data-table/data-table.component.spec.ts
  src/app/shared/components/data-table/data-table.component.ts
  src/app/shared/shared.module.ts
  src/styles.scss
Labels: enhancement

#298 Sidenav performance fix
  src/app/root/root.module.ts
  src/app/shared/components/data-display/data-display.component.html
  src/app/shared/components/data-display/data-display.component.spec.ts
  src/app/shared/components/data-display/data-display.component.ts
  src/app/shared/components/loader/loader.component.html
  src/app/shared/components/loader/loader.component.scss
  src/app/shared/components/loader/loader.component.spec.ts
  src/app/shared/components/loader/loader.component.ts
  src/app/shared/shared.module.ts
  src/app/volunteer-system/containers/check-in/check-in.component.scss
Labels: enhancement

#300 Dynamically select data table css given isEditable
  src/app/shared/components/data-table/data-table.component.html
  src/app/shared/components/data-table/data-table.component.scss
  src/app/shared/components/data-table/data-table.component.spec.ts
  src/app/shared/components/data-table/data-table.component.ts
Labels: bug

#308 Pass in member role and id when updating member
  src/app/auth/effects/session.effects.ts
  src/app/public/public.module.ts
  src/app/shared/components/user-form/user-form.component.spec.ts
  src/app/shared/components/user-form/user-form.component.ts
Labels: bug

#309 Settings sites
  src/app/core/services/site.service.spec.ts
  src/app/core/services/site.service.ts
  src/app/core/services/snack-bar.service.spec.ts
  src/app/core/services/snack-bar.service.ts
  src/app/public/components/email-dialog/email-dialog.component.ts
  src/app/public/effects/sign-up-effects.service.ts
  src/app/settings/actions/settings.actions.spec.ts
  src/app/settings/actions/settings.actions.ts
  src/app/settings/components/site-dialog/site-dialog.component.html
  src/app/settings/components/site-dialog/site-dialog.component.scss
  src/app/settings/components/site-dialog/site-dialog.component.spec.ts
  src/app/settings/components/site-dialog/site-dialog.component.ts
  src/app/settings/containers/settings-page/settings-page.component.html
  src/app/settings/containers/settings-page/settings-page.component.spec.ts
  src/app/settings/containers/site-settings/site-settings.component.html
  src/app/settings/containers/site-settings/site-settings.component.scss
  src/app/settings/containers/site-settings/site-settings.component.spec.ts
  src/app/settings/containers/site-settings/site-settings.component.ts
  src/app/settings/containers/visits/visits.component.html
  src/app/settings/containers/visits/visits.component.spec.ts
  src/app/settings/containers/visits/visits.component.ts
  src/app/settings/effects/settings.effects.spec.ts
  src/app/settings/effects/settings.effects.ts
  src/app/settings/selectors/settings.selectors.ts
  src/app/settings/settings.module.ts
  src/app/shared/components/data-cell/data-cell.component.spec.ts
  src/app/shared/components/data-cell/data-cell.component.ts
  src/app/shared/components/data-table/data-table.component.html
  src/app/shared/components/data-table/data-table.component.scss
  src/app/shared/components/data-table/data-table.component.spec.ts
  src/app/shared/components/data-table/data-table.component.ts
  src/app/shared/models/column-options.ts
  src/app/shared/models/site.ts
  src/mocks/objects/site.mock.ts
  src/styles.scss
  yarn.lock
Labels: feature
